# Generated by Django 3.0.8 on 2020-07-25 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MovieInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movieTitle', models.CharField(max_length=50)),
                ('movieGenre', models.CharField(max_length=10, unique=True)),
                ('movieImage', models.ImageField(blank=True, upload_to='images/')),
            ],
        ),
    ]
