# Generated by Django 3.0.8 on 2020-07-25 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movieinfo',
            name='movieGenre',
            field=models.CharField(max_length=10),
        ),
    ]
